spool C:\Users\itiwari\Desktop\CREATE.txt
CREATE TABLE EMP_NAMES ( id INT PRIMARY KEY, name VARCHAR(20) );
INSERT INTO EMP_NAMES VALUES ( 1, 'Alpha' );
INSERT INTO EMP_NAMES VALUES ( 2, 'Beta' );
INSERT INTO EMP_NAMES VALUES ( 3, 'Gamma' );
INSERT INTO EMP_NAMES VALUES ( 4, 'Ele' ); 
CREATE TABLE EMP_CONTACT ( id INT PRIMARY KEY, contact INT );
INSERT INTO EMP_CONTACT VALUES ( 1, 8094989700 );
INSERT INTO EMP_CONTACT VALUES ( 2, 7896750090 );
INSERT INTO EMP_CONTACT VALUES ( 3, 8903321456 );
INSERT INTO EMP_CONTACT VALUES ( 4, 8902211134 );
/
spool off;
